### ISSUE TITLE
Failure to update

### ISSUE THREAD

**Issue by peaveyman** [NuLogicSystems/PKGBUILD#4]
When trying to update I get this: 

warning: enlightenment: ignoring package upgrade (0.21.10-2 => 0.22.0-1)
�resolving dependencies...
warning: ignoring package enlightenment-0.22.0-1
warning: cannot resolve "enlightenment>=0.22.0", a dependency of "clipboard"
:: The following package cannot be upgraded due to unresolvable dependencies:
      clipboard

:: Do you want to skip the above package for this upgrade? [y/N]�

That's with the package on hold. If I take it off hold I get this: 

screenshot: installing enlightenment (0.22.0-1) breaks dependency 'enlightenment<0.21.99'

**Comment by NuLogicSystems** [comment]
Yes, this requires 0.22.0, it does not run on git..

**Comment by peaveyman** [comment]
So, what's the solution here?

**Comment by NuLogicSystems** [comment]
Either run released versions of EFL / E, or don't try installing external gadgets.

**Comment by NuLogicSystems** [comment]
This is not a bug (issue).

**Comment by peaveyman** [comment]
I wanted to try bryce but after adding it there were very few gadgets available for it.

**Comment by NuLogicSystems** [comment]
You must have tried it on 0.21 and earlier. There are quite a few now, and more to come in the future.
However, don't expect a taskmanager or systemtray, these are on the do not implement list. Taskmanager functionality is in launcher, and sni (appindicator) support will be added directly into bryce so that they look like and function as if they were native gadgets.

**Comment by NuLogicSystems** [comment]
So far the only 3rd party module updated for e 0.22 is clipboard, I'll update the others when I get a chance to test them.

**Comment by NuLogicSystems** [comment]
All of robs (3rd party) modules updated to enlightenment 0.22.x now.
You should have no more issues.
NOTE: clipboard received an epoch back to old version, the new wayland compatible fork is not ready yet..

**Comment by peaveyman** [comment]
The reason I had held was because it was wanting to update clipboard and screenshot and wouldn't because of the version issue.

**Comment by NuLogicSystems** [comment]
Ah, I see. Well, everytime Enlightenment gets a version update, all modules need to be rebuilt as well. Sometimes just recompiling them against the new version works, other times they need reworked as well. I just hadn't had enough time to recompile and test them all, that's all.
